sudo: false
language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: bgwojSpDD7bqnEt2OqMxNcvTZ4/isXfULkukRDXS1d4HK2Eh6F4f7aYz+h1OaQisQpYeDsbbpljpOhkvUxSXW9a9FSNrkb/T0InexsgtzmpJKDLHwf2w/Lsaih+fB924dLfh+w1SPqQx5Tch+u0pfWJwDHVFx+h68CxX/K6T9p8SBv1eS36I4nGqWlFy8H4hfNLr7ghVoYxglCPOX5rC9Y6qg7VLLvl5De76lXkUj/khYoZwj92QI9n4bM+ysJSg+kYx9JwwQ2tkCMCDqJkZ7xscokRTgsJ3Qk5KsLuLiLmXftEJhaXOikLRMBlCcI5dJxyxjImsO8edaK9W7ePvS+/IrrmPj9BlCktsHG0QRK8j8OrrP/1Mn3TDmXPqAM83RLzZ1cvV9OT6hWHgudwa4BwWjNkWDhTfJHL3f0g88rJFtp2JiwzozzkHwyesb1ysMBvv8wqYf1YTLppiriFO0Ho+3jVq/fLeVQjrAGqBaRsRIQ3uEA5Dy8rZMgaE1Z8L02wzzWnT9kxValVRAKLYVfBNcb1twI/taMFTCJ/0NqVcuoCXAmZXBr+TTHy7+Q0QpKgu4skozG4ivqr0NdNXDxct0eWYn9aUMg/RGmronFAKRGwh5DhkJR+IJ7H6S4ZohDYQdnLBUhSOrN4gAZG5Sc2Hw43U3Y26q5Pa9Opuj9c=
