sudo: false
language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: gSx1W1aXxe+AEPenzBZBmHZ+U35uUILNukypbVRKd8XhRhzYZkDtNQmy+1yPv0CLhcEgVpMAkMUulYVxoak4ukj9CJeDG8nmFTzi0rU+u+46n0hQWHgL5av/v4OCYH6Od3sPuCxSUVlmLvlh3yaanXJOkRDrMn4taw0y0bSvgQ23vYRaosaYOyIRJm34jCKwl4sFkviWT65DgjFIJS4I+rH//QGumQFvyo8fVosV+ob7q4yFUStAvCMiQmAcl5B4C3LHdpsObKdDjQzR2nLzdmyMFwSEq9kW6yw+ovOssjhUUSNb5wZQJ5gUiuxujHepapFWl+exn5yws1Rweljk6q/IvtFpwuHImaplFd1UFzQvUrC/56VGqAMoF2l5zkLEpJhTCBDliLGYHdq3C7by+5EQyzGD7aqPXGkf4BbdBydSmV8o1jb5ftg+xCuT7Tm4gHL5HC2Sl2ZGYA5EYtHP0ZQiK/PadWxeX+ySBDkvo+fzaKwYSMxCInytxbIQrL3D64UkzryIiOCo0THkhD+weyu/uwUNKOxR+ASmCgA7JURgvxWTtu0DXfUymlafb5imOttqOHVbES5dsh2pystqIGO+Cc2WY4QFz6PsqsmUZn1t8UxdTrBqXcOxLgZYIrsCgAbfCRpJJH86MJoWGDoJB6YweXMlzTlb67BvuPLusLU=
  app: helloboot
  on: master
