sudo: false
language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: SLJSuranelHL+ClkEAVcySGwQOarqONRObceKZhgeK0aFK5S1BE9dtnXGHDwaLFER2FXUgDcrATvTWA726LdsWT7uDfqSx0I9X1sgDCixCJcN21X86hRZhQ1Ztg694T/Ip0hP5Ysvhpt9dsKqu1EfEl5+8Bp5EGm/wxHdohwIr7TTy7PEoiqg47iFOqQRZjOUU/RD0gp/5oq/FrmYIZsaH/QgVDk+TSEMJL3SKXembontm8MZOEiQTmOaoYPuPNJBS15bkyYOfCXSrIQFvUR6pC/ztBeZgyIsii7art6K3D/F5+6DX2BgkPBPco9HpQDiU1iutvjWFcqzI9c02H/i3P2861jC59Qgq/3jevsvskSWlrpiLjHNU6uPqhKMGKrocG6odQFilimjoBAIll1V7fbRKrAjz2F2svUvwuiliB8rpWFyo20dj3TD7UyvUKGXl6UQfMvsNwyWSdicoteqxMJRmxItXN85HOEOde2p66zk/SV1TcMgeNnYZKE/ShxRg1gFzSi8IBwantaRcL4hogUc+0rJxVI5qXwLn7z2oa0V5lHjqBRJ83uet40K0A5CHBs0T9xkxPkXPdhY3kCU8Fj7Olbxj0OyE5LxVgFQ+MY256pjtbs0GotaNmJkUA6Ammuz0/nsv6ExqLf0G5/KOdD5JVepvEkpb9ch58cYFE=
  app: helloboot
  on:
    repo: TheArk3stry/helloboot
