sudo: false
language: java
jdk:
- oraclejdk8
deploy:
  api_key:
    secure: aWf+EyVterOAiSwbJaAwJXRvV4/Aef/O9zcdLNu8Or4ofvQ+997RXQiBemHVo244+t+AUS0TqqVlRqQZp5bFqce5+ikW/Xe6tgmYKm6lljUV8Sg6uJtYcWkGVjJR03g/qvFAqH6kYcgPlnYX0AjejKslrqRS5igbHh3Of7UbQfBx4FIIBCl2xGxINVep87hCVbC8q0vV19wxuNC3kP/0S9uD8x9U3gE2xyWSX5WBB2WTQep08eISeCDGpFhmCBJVY6YDQ45C9DUjz2+joOY1aDNhoEBVGQ794OW83Xk6lU8RQXo4wLpuMg3s9vICLXK24WFYWrbgWcJCUB1pjWD757YT8DWc6pZ4FnUTnu4towH7b6kfiJLhY0dZtE7QwBAud2hegXdm5DOrKYuE6REUiZrSzfX3zyeXSmDUCwc1L+b0uTJzWRHBmxPzI728eTB/QY9cw0QAEoexdfmchm6U0oTpzNe7Yvy+LY2OXLFrv/5yqvJ8H6wrHLIh4RjHlefmzBgt/OrW9w3rSlgN87iIr4GKjQeMUDU4uxRAUnQVpVjnaUrh89uaMjQeCtMOarz2Fe/6KZsq6f1Qw6FwkwTLWrpfQ5QS/EXVg7HgTi97x0z3dQhDzrcDdJ3ZjtAGY/yYzW3p0eVYzNpf8ge0hJr3xpihOg/B438zbsHlZfHeO5E=
